src/library/entities/Library.java
I have added a file header comment section at the top of the file where we can find the who is the author, mediator, and reviewer for the file. 
Please review and let me know what you think
=> LMS-HDK-01-Adding file header comment in Library entity file

src/library/entities/Book.java, src/library/entities/Member.java
Instance variable names changed according to the style guidelines.
Author: Chelaka
Mediator: Avishka
Reviewer: Harsha
=> Chelaka bhf

src/library/entities/Library.java
Update instance variables in Library entity
=> LMS-HDK-PR-04-Update instance variables in Library entity

src/library/entities/Book.java
Changed the enum according to the code style guidelines.
Chelaka
=> Changed the enum according to the code style guidelines

src/library/entities/Book.java
Updated the toString method according to code style guidelines
chelaka
=> Updated the toString method according to code style guidelines

src/library/entities/Book.java
Updated the getId method according to code style guidelines
Chelaka
=> Updated the getId method according to code style guidelines

src/library/entities/Member.java
cloning from master to chelaka_BHF
Chelaka
=> cloning from master to chelaka_BHF

src/library/entities/Member.java
Get Latest from the master branch
=> Get Latest from the master branch

src/library/entities/Library.java
Refactor the code according to the code style guidelines which recorded in save method in the Library class
=> LMS-HDK-PR -Update implantation method name of Save in Library class

src/library/entities/Book.java
Updated the getTitle method according to code style guidelines
Chelaka
=> Updated the getTitle method according to code style guidelines

src/library/entities/Book.java, src/library/entities/Library.java
merging latest changes from the master branch
=> merging latest changes from the master branch

src/library/entities/Library.java
Refactoring getter method in library class file
=> LMS-HDK-PR -Refactoring getter method in library class file

src/library/entities/Book.java
Updated the isAvailable() method according to code style guidelines
Chelaka
=> Updated the isAvailable() method according to code style guidelines

src/library/entities/Book.java
Updated isOnLoan() method in Book.java according to code style guidelines.
Chelaka
=> Updated isOnLoan() method in Book.java according to code style guidelines.

src/library/entities/Calendar.java
Get the latest changes from master
=> Get the latest changes from master

src/library/entities/Book.java
Updated isDamaged method according to code style guidelines in Book.java
Chelaka
=> Updated isDamaged method according to code style guidelines in Book.java

src/library/entities/Book.java
Updated borrow method according to code style guidelines in Book.java
Chelaka
=> Updated borrow method according to code style guidelines in Book.java

src/library/entities/Calendar.java
Get Latest to harsha_DK branch
=> LMS-HDK-PR-08 -Get Latest to harsha_DK branch

src/library/entities/Calendar.java
getting the latest code from master to my branch
=> clonning from master to niharika

src/library/entities/Book.java
LMS-BHC-PR-10-Updated the Return method according to code style guidelines in Book.java
Chelaka
=> LMS-BHC-PR-10-Updated the Return method according to code style guidelines in Book.java

src/library/entities/Library.java
@NiharikaGavvala  I have refactored get Library member method and get books catalog  @method in Library class file,
Please ask Chelaka to review the changes.
=> LMS-HDK-PR-07 -Refactoring get Library member method and get books catalog method in Library class file

src/library/entities/Calendar.java
@ChelakaFernando Can you please ask harsha to review this. Thank you.
=> LMS-NG-PR-16 -Refactoring get date method in calendar.java

src/library/entities/Calendar.java
LMS-BHC-PR-11-Cloning from master to chelaka_BHF
Chelaka
=> LMS-BHC-PR-11-Cloning from master to chelaka_BHF

src/library/entities/Library.java
@NiharikaGavvala I have refactored the  get booking loan method in library class file 
Please ask Chelaka to review the changes and approve
=> LMS-HDK-PR-09 -Refactoring get booking loan method in library class file 

src/library/entities/Book.java
LMS-BHC-PR-11-Updated the Repair method according to code style guidelines in Book.java
=> LMS-BHC-PR-11-Updated the Repair method according to code style guidelines in Book.java

src/library/fixbook/FixBookControl.java
LMS-BHC-PR-32-Updated scanBook method in FixBookControl.java
=> LMS-BHC-PR-32-Updated scanBook method in FixBookControl.java

src/library/borrowbook/BorrowBookUI.java
@ChelakaFernando I have change done change on Refactoring BorrowBookUI constructor in BookUI class file
Ask @NiharikaGavvala to review the changes
=> LMS-HDK-PR-30 -Refactoring BorrowBookUI constructor in BookUI class file

src/library/fixbook/FixBookControl.java
LMS-BHC-PR-34-Updated the checkFixBook method
=> LMS-BHC-PR-34-Updated the checkFixBook method

src/library/entities/Loan.java
@ChelakaFernando i have updated the loan.java and it's completed. Please ask harsha to review.
=> LMS-NG-PR-110-updated loan.java

src/library/payfine/PayFineControl.java
LMS-BHC-PR-36-Update the variable names according to the code style guidelines
=> LMS-BHC-PR-36-Update the variable names according to the code style guidelines

src/library/payfine/PayFineControl.java
LMS-BHC-PR-38-Updated PayFineControl constructor
=> LMS-BHC-PR-38-Updated PayFineControl constructor

src/library/payfine/PayFineControl.java
LMS-BHC-PR-40-Updated setUi method
=> LMS-BHC-PR-40-Updated setUi method

src/library/Main.java
@harshadilupkumara can you please ask chelaka to review the changes that have been done to main.java.
=> LMS-NG-PR-119-Refactored main class

src/library/borrowbook/BorrowBookUI.java
I have done the changes on refactoring displayObject in BorrowBookUI class file
Ask @NiharikaGavvala review the changes
=> LMS-HDK-PR-36-Refactoring displayObject in BorrowBookUI class file

src/library/entities/Member.java
LMS-BHC-PR-41-Added the author name comment for necessary changes Member.java
=> LMS-BHC-PR-41-Added the author name comment for necessary changes Member.java

src/library/payfine/PayFineControl.java
LMS-BHC-PR-43-Updated the cardSwiped method
=> LMS-BHC-PR-43-Updated the cardSwiped method

src/library/fixbook/FixBookUI.java
I have refactored on Adding header comment in FixBookUI class file
Aske @NiharikaGavvala to review it
=> LMS-HDK-PR-38-Adding header comment in FixBookUI class file

src/library/payfine/PayFineControl.java
LMS-BHC-PR-45-Updated setCancel method
=> LMS-BHC-PR-45-Updated setCancel method

src/library/fixbook/FixBookUI.java
I have done the changes on refactoring instance variable  in FixBookUI class file
please asked @NiharikaGavvala  review it
=> LMS-HDK-PR-38- refactoring instance variable  in FixBookUI class file

src/library/payfine/PayFineControl.java
LMS-BHC-PR-47-Updated the payFine method
=> LMS-BHC-PR-47-Updated the payFine method

src/library/fixbook/FixBookUI.java
I have done the changes on refactoring FixBookUI  constructor  in FixBookUI class file
Ask @NiharikaGavvala  to review the changes
=> LMS-HDK-PR-39- refactoring FixBookUI  constructor  in FixBookUI class file

src/library/returnBook/ReturnBookControl.java
LMS-BHC-PR-49-Updated the instance variables
=> LMS-BHC-PR-49-Updated the instance variables

src/library/returnBook/ReturnBookControl.java
LMS-BHC-PR-51-Updated the ReturnBookControl constructor
=> LMS-BHC-PR-51-Updated the ReturnBookControl constructor

src/library/fixbook/FixBookUI.java
I have done the changes on refactoring FixBookUI  constructor  in FixBookUI class file
please ask @NiharikaGavvala  to review the changes
=> LMS-HDK-PR-41- refactoring FixBookUI  constructor  in FixBookUI class file

src/library/Main.java
@harshadilupkumara can you please ask chelaka to review the changes that have made in main.java.
=> LMS-NG-PR-139-refactored the while method in main.java

src/library/returnBook/ReturnBookControl.java
LMS-BHC-COM-53-Updated the setUi method in ReturnBookControl.java
=> LMS-BHC-PR-53-Updated the setUi method in ReturnBookControl.java

src/library/fixbook/FixBookUI.java
I have done the changes on refactoring displayOutPut, displayObject in FixBookUI class
Ask @NiharikaGavvala  to do the changes
=> LMS-HDK-PR-43- refactoring displayOutPut, displayObject in FixBookUI class

src/library/fixbook/FixBookUI.java
@ChelakaFernando
I have done the changes on refactoring runFixBook method in FixBookUI class file
Ask @NiharikaGavvala to review the changes
=> LMS-HDK-PR-44- refactoring runFixBook method in FixBookUI class file

src/library/Main.java
@harshadilupkumara can you please ask chelaka to review the changes made in main.java.
=> LMS-NG-PR-50-methods changed in main.java

src/library/payfine/PayFineUI.java
I have change on updating  member variable in PayFineUI class file
Ask @NiharikaGavvala  to review the changes
=> LMS-HDK-PR-45- updating  member variable in PayFineUI class file

src/library/returnBook/ReturnBookControl.java
LMS-BHC-PR-55-Updated scanBook method in ReturnBookControl.java
=> LMS-BHC-PR-55-Updated scanBook method in ReturnBookControl.java

src/library/returnBook/ReturnBookControl.java
LMS-BHC-PR-57-setScanningComplete method updated in ReturnBookControl.java
=> LMS-BHC-PR-57-setScanningComplete method updated in ReturnBookControl.java

src/library/payfine/PayFineUI.java
@ChelakaFernando
I have done changes on updating PayFineUI constructor in PayFineUI class file
please ask @NiharikaGavvala  to review the changes
=> LMS-HDK-PR-47- updating PayFineUI constuctor in PayFineUI class file

src/library/Main.java
@harshadilupkumara  i have changed list members, fix book, borrow book methods changed in java. Please ask chelaka to review it.
=> LMS-NG-PR-55-private methods changed in main.java

src/library/returnBook/ReturnBookControl.java
LMS-BHC-PR-59-Update dischargeLoan method in ReturnBookControl.java
=> LMS-BHC-PR-59-Update dischargeLoan method in ReturnBookControl.java

src/library/payfine/PayFineUI.java
I have done the changes on updating runPayFine method in PayFineUI class file 
Ask @NiharikaGavvala  to do the review
=> LMS-HDK-PR-49- updating runPayFine method in PayFineUI class file 

src/library/Main.java
@harshadilupkumara can you please ask chelaka to review the changes.
=> LMS-NG-PR-60-changed the incrementDate and addBook in main.java

src/library/Main.java
@harshadilupkumara can you ask chelaka to review it.
=> LMS-NG-PR-63-refactored the string method

src/library/borrowbook/BorrowBookUI.java, src/library/fixbook/FixBookUI.java
I have done the changes on updating  getInput method related to code guideline
Ask @NiharikaGavvala to review the changes
=> LMS-HDK-PR-52- updating  getInput method related to code guideline

src/library/returnBook/ReturnBookUI.java
@harshadilupkumara can you please ask chelaka to review it.
=> LMS-NG-PR-88-changed the enum and RetrunBookUi 

src/library/returnBook/ReturnBookUI.java
@NiharikaGavvala 
I have done the changes on  updating runReturnBook method in ReturnBookUI class
Ask @ChelakaFernando do the review
=> LMS-HDK-PR-53- I have done the changes on  updating runReturnBook method in ReturnBookUI class

src/library/returnBook/ReturnBookUI.java
@harshadilupkumara please ask chelaka to review the code.
=> LMS-NG-PR-83-changed the methods in ReturnBookUi.java

src/library/payfine/PayFineControl.java
LMS-BHC-PR-62-Updated the author details
=> LMS-BHC-PR-62-Updated the author details

src/library/returnBook/ReturnBookUI.java
@ChelakaFernando can you review please, I have updated the author details.
=> LMS-NG-PR-121-updated the author details in ReturnBookUI.java

src/library/borrowbook/BorrowBookUI.java
@NiharikaGavvala 
I have an update on  comment headline  borrowbook UI class
please review and approve the changes
=> LMS-HDK-PR-55- updating comment head line  borrowbook UI class
